# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
