# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_subscribes',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_subscribes',
            field=models.ManyToManyField(to='post.Profile'),
        ),
    ]
